//jogs
export const FETCH_JOGS_START = 'FETCH_JOGS_START';
export const FETCH_JOGS_SUCCESS = 'FETCH_JOGS_SUCCESS';
export const FETCH_JOGS_ERROR = 'FETCH_JOGS_ERROR';
export const CREATE_JOG_START = 'FETCH_JOGS_START';
export const CREATE_JOG_SUCCESS = 'FETCH_JOGS_SUCCESS';
export const SAVE_FILTERED_JOGS = 'SAVE_FILTERED_JOGS';
export const REDIRECT_TO_URL = 'REDIRECT_TO_URL';
export const REDIRECT_TO_URL_SUCCESS = 'REDIRECT_TO_URL_SUCCESS';
export const CHANGE_SHOW_DATE_FILTER_VALUE = 'CHANGE_SHOW_DATE_FILTER_VALUE';
//menu
export const CHANGE_MOBILE_MENU_VISIBILITY = 'CHANGE_MOBILE_MENU_VISIBILITY';
//main
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';
